import Head from 'next/head'
import { useState } from 'react';

export default function Home() {

  const [color, setColor] = useState()

  const changeFilter = (color) => {
    setColor(color)
  }

  return (
    <div>
      <Head>
        <title>RGB camera filter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div class="wrapper">
          <video id="videoFeed" playsInline autoPlay loop muted controls={false}></video>
          <div id="filter-color" className={"filter " + color}></div>
          <div className='filters-wrapper'>
            <div class="filters">
              <div className={"filter-button " + (!color && 'current')} style={{ backgroundColor: "rgba(255,255,255,1)" }} onClick={() => changeFilter()}> </div>
              <div className={"filter-button " + (color == 'red' && 'current')} style={{ backgroundColor: "rgba(255,0,0,1)" }} onClick={() => changeFilter('red')}> </div>
              <div className={"filter-button " + (color == 'green' && 'current')} style={{ backgroundColor: "rgba(0,255,0,1)" }} onClick={() => changeFilter('green')}> </div>
              <div className={"filter-button " + (color == 'blue' && 'current')} style={{ backgroundColor: "rgba(0,0,255,1)" }} onClick={() => changeFilter('blue')}> </div>
            </div>
          </div>
        </div>
      </main>
      <script src="/script.js" async />
    </div>
  )
}
